# ulab Demo
Here there will be simple examples about ulab usage.

In [1]:
%serialconnect -p /dev/ttyUSB0 --baudrate 115200

Connecting to --port=/dev/ttyUSB0 --baud=115200 
Ready.


In [2]:
import ulab as np

In [3]:
help(np)

object <module 'ulab'> is of type module
  __name__ -- ulab
  __version__ -- 0.262
  array -- <class 'ndarray'>
  size -- <function>
  inv -- <function>
  dot -- <function>
  zeros -- <function>
  ones -- <function>
  eye -- <function>
  det -- <function>
  eig -- <function>
  acos -- <function>
  acosh -- <function>
  asin -- <function>
  asinh -- <function>
  atan -- <function>
  atanh -- <function>
  ceil -- <function>
  cos -- <function>
  erf -- <function>
  erfc -- <function>
  exp -- <function>
  expm1 -- <function>
  floor -- <function>
  gamma -- <function>
  lgamma -- <function>
  log -- <function>
  log10 -- <function>
  log2 -- <function>
  sin -- <function>
  sinh -- <function>
  sqrt -- <function>
  tan -- <function>
  tanh -- <function>
  linspace -- <function>
  sum -- <function>
  mean -- <function>
  std -- <function>
  min -- <function>
  max -- <function>
  argmin -- <function>
  argmax -- <function>
  roll -- <function>
  flip -- <function>
  diff -- <function>
  s

In [4]:
help(np.array)

object <class 'ndarray'> is of type type
  shape -- <function>
  rawsize -- <function>
  flatten -- <function>
  asbytearray -- <function>
  transpose -- <function>
  reshape -- <function>
  sort -- <function>


In [5]:
help(np.fft)

object <function> is of type function


In [6]:
print(np.cos(180))

-0.5984601


In [7]:
print(np.cos(np.pi))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'pi'


In [8]:
import math

In [9]:
print(np.cos(math.pi))

-1.0


In [10]:
a=np.array([1,2,3])

In [11]:
a

In [12]:
print(a)

array([1.0, 2.0, 3.0], dtype=float)


In [13]:
a=np.array([1,2,3],dtype=uint8)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'uint8' isn't defined


In [14]:
a=np.array([1,2,3],dtype=np.uint8)

In [15]:
print(a)

array([1, 2, 3], dtype=uint8)


In [16]:
a=np.array([1,2,3,4],[5,6,7,8],dtype=np.uint8)

In [17]:
print(a)

array([1, 2, 3, 4], dtype=uint8)


In [18]:
a=np.array([1,2,3,4],[5,6,7,8])

In [19]:
print(a)

array([1.0, 2.0, 3.0, 4.0], dtype=float)


In [20]:
a=np.array(([1,2,3,4],[5,6,7,8]),dtype=np.uint8)

In [21]:
print(a)

array([[1, 2, 3, 4],
	 [5, 6, 7, 8]], dtype=uint8)


In [22]:
b=np.array([1,2,3], dtype=np.uint8)

In [23]:
a=np.array([b,b],[b,b],dtype=np.uint8)

In [24]:
print(a)

array([[1, 2, 3],
	 [1, 2, 3]], dtype=uint8)


In [25]:
a=np.array(([b,b],[b,b]),dtype=np.uint8)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert ndarray to int


In [26]:
print(a.shape())

(2, 3)


In [27]:
print(a.flatten())

array([1, 2, 3, 1, 2, 3], dtype=uint8)


In [28]:
print(a[3])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index is out of bounds


In [29]:
print(a[1])

array([1, 2, 3], dtype=uint8)


In [30]:
def timeit(f,*args, **kwargs):
    import utime
    func_name=str(f).split(' ')[1]
    def new_func(*args,**kwargs):
        t=utime.ticks_us()
        result=f(*args,**kwargs)
        print('execution time: ', utime.ticks_diff(utime.ticks_us(),t),' us')
        return result
    return new_func

In [31]:
@timeit
def sort_time(array):
    return np.sort(array)

In [32]:
b=np.sin(np.linspace(0,6.28, num=1000))
print('b: ',b)

b:  array([0.0, 0.006286245, 0.01257224, ..., -0.01578295, -0.009497325, -0.003211318], dtype=float)


In [33]:
sort_time(b)

execution time:  2870  us


In [34]:
print(b)

array([0.0, 0.006286245, 0.01257224, ..., -0.01578295, -0.009497325, -0.003211318], dtype=float)


In [35]:
@timeit
def linspace_creator():
    return np.sin(np.linspace(0,6.28, num=1000))

In [36]:
b=linspace_creator()

execution time:  2704  us


In [37]:
b=linspace_creator()

execution time:  2197  us


In [38]:
b=linspace_creator()

execution time:  2224  us


In [39]:
@timeit
def linspace_creator():
    b=np.sin(np.linspace(0,6.28, num=1000))
    return np.sort(b)

In [40]:
b=linspace_creator()

execution time:  5128  us


In [41]:
print(b)

array([-0.9999972, -0.9999922, -0.9999629, ..., 0.9999751, 0.9999848, 1.0], dtype=float)
